<a href="https://colab.research.google.com/github/JamieBali/sudoku/blob/main/SA_Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
import numpy as np
import random, math, statistics

In [2]:
trivial = [[8,9,1,2,7,0,5,6,3],[6,0,3,1,8,5,9,0,0],[4,5,7,6,3,9,0,0,2],[5,0,6,4,1,7,2,3,0],[7,0,2,9,0,3,8,1,6],[3,1,0,0,2,6,0,5,4],[9,3,8,5,4,0,6,7,0],[1,6,4,0,9,0,3,2,5],[0,7,5,3,6,1,4,9,8]]

# this is a very simple 4x4 sudoku from sudoku.com
four = [[0,3,4,0],[4,0,0,2],[1,0,0,3],[0,2,1,0]]

# these three were taken randomly from sudoku.com
easy = [[0,0,0,0,7,9,0,3,0],[5,0,2,0,6,1,4,7,8],[3,7,6,0,8,5,9,0,2],[0,1,7,5,0,0,8,0,0],[2,0,9,8,3,0,0,0,0],[0,0,0,0,2,0,0,4,0],[0,0,0,0,5,0,2,0,1],[0,2,3,0,0,0,0,5,4],[1,0,0,7,0,0,0,0,0]]
medium = [[0,3,1,0,5,0,0,2,0],[0,0,0,0,0,2,9,0,5],[2,0,0,0,1,0,0,0,0],[3,5,0,0,9,0,0,7,0],[7,0,0,5,0,0,0,4,0],[0,1,0,7,0,3,2,0,0],[1,2,6,3,0,0,0,0,0],[0,9,0,8,0,5,0,0,0],[5,0,0,0,2,0,7,0,0]]
hard = [[0,4,0,0,0,5,0,6,0],[0,0,5,4,2,0,0,0,0],[0,0,1,6,0,3,5,0,4],[0,0,0,0,0,0,7,0,0],[0,3,7,0,0,0,0,1,0],[9,0,0,0,0,4,3,5,0],[0,0,4,2,5,0,0,0,0],[0,0,0,0,0,0,0,7,6],[6,0,9,0,7,0,0,0,5]]

# this is a 25x25 sudoku taken from an old c programming forum in from 2006 https://cboard.cprogramming.com/cplusplus-programming/117005-25x25-sudoku.html
twentyfive = [[0,0,12,6,0,0,7,0,18,0,5,24,0,10,1,0,0,4,0,0,0,0,0,0,0], [2,0,19,0,13,0,0,0,10,0,0,0,0,0,0,0,0,18,5,0,0,0,0,0,1], [0,0,0,0,0,0,0,22,0,0,0,0,3,0,2,0,0,14,12,0,16,8,25,0,0],[0,16,0,0,0,2,23,0,0,13,12,22,0,0,0,21,15,19,3,0,0,0,0,14,0],[23,0,24,0,0,0,0,0,25,8,4,0,16,19,21,0,0,7,0,0,0,3,12,0,9],[0,4,0,2,0,0,0,0,0,0,0,10,0,24,12,17,16,0,0,0,5,0,0,0,0],[0,0,9,0,0,6,25,0,0,0,8,0,5,3,0,0,0,0,0,0,20,0,0,18,19],[15,0,10,11,0,0,0,18,12,19,0,0,0,0,0,0,0,23,0,0,7,0,0,4,0], [0,0,0,0,0,0,0,14,0,22,0,0,18,16,20,0,6,11,13,0,0,0,0,0,0], [0,22,0,25,0,0,1,17,5,4,7,0,0,14,0,8,3,21,0,0,11,0,0,0,6], [0,20,13,15,0,0,0,0,0,0,9,0,0,2,0,25,0,1,8,0,0,5,0,21,0], [0,1,0,0,0,0,16,10,0,7,0,0,4,20,0,0,9,0,0,14,0,24,0,17,0], [25,2,5,0,0,0,0,0,13,0,0,0,0,0,22,0,0,0,0,0,19,1,8,0,0], [0,0,7,21,0,0,12,0,2,17,0,0,0,18,6,16,0,0,15,0,0,13,0,10,0], [8,10,18,12,16,9,0,0,0,5,0,0,0,0,19,0,0,17,0,21,0,15,0,0,22], [0,8,0,0,15,0,3,0,6,0,21,0,0,7,0,18,14,5,0,1,0,0,0,0,0], [0,0,0,19,0,1,0,16,11,0,0,0,10,22,25,15,0,0,0,0,0,0,21,0,0], [0,3,1,0,21,0,0,4,0,0,0,0,2,0,13,0,24,25,0,0,14,0,0,6,0], [0,0,0,0,0,0,0,15,0,12,14,0,6,17,24,0,0,0,0,0,0,0,13,0,0], [0,5,23,16,4,0,13,24,7,2,0,9,0,0,15,3,0,22,0,0,0,0,0,0,8], [0,0,25,20,2,0,19,0,0,0,0,1,0,0,0,0,21,3,0,0,12,0,0,0,0], [16,12,0,5,0,11,21,0,23,0,0,15,0,0,0,0,19,9,0,0,0,0,0,25,10], [0,0,0,0,9,20,22,7,4,0,3,0,14,25,18,0,11,0,0,0,0,0,1,0,15], [24,0,6,0,22,8,0,25,14,0,10,11,0,9,0,20,1,16,0,7,0,23,0,0,13], [14,13,21,1,0,0,5,0,0,0,6,0,22,0,23,10,0,0,0,2,0,0,18,7,11]]

# this is the solved version of the "easy" sudoku above.
solved = [[8,4,1,2,7,9,6,3,5],[5,9,2,3,6,1,4,7,8],[3,7,6,4,8,5,9,1,2],[4,1,7,5,9,6,8,2,3],[2,5,9,8,3,4,1,6,7],[6,3,8,1,2,7,5,4,9],[7,6,4,9,5,3,2,8,1],[9,2,3,6,1,8,7,5,4],[1,8,5,7,4,2,3,9,6]]

# Simulated Annealing

In [19]:
class simulatedAnnealing():
  def __init__(self, puzzle, size, cooling_rate):
    self.size = size
    self.puzzle, self.pick_options = self.randomly_fill(np.copy(puzzle))
    self.cooling_rate = cooling_rate
    self.err = 0
    self.temperature = 2.51
    self.energy = self.get_energy(self.puzzle)
    self.itterations = sum([int(x != 0) for x in np.copy(puzzle).flatten()])

  def randomly_fill(self, puzzle):
    rt = int(math.sqrt(self.size))
    pick_options = []
    for x_itt in range(rt):
      for y_itt in range(rt):
        block = []
        temp_options = []
        for x in range(rt):
          for y in range(rt):
            nx = (x_itt * rt) + x
            ny = (y_itt * rt) + y
            if puzzle[nx][ny] == 0:
              temp_options.append([nx, ny])
            else:
              block.append(puzzle[nx][ny])
        if len(temp_options) == 1:
          for x in range(1, self.size + 1):
            if x not in block:
              puzzle[temp_options[0][0]][temp_options[0][1]] = x
          temp_options = []
        else:
          for pos in temp_options:
            temp = []
            for i in range(1, self.size + 1):
              if i not in block:
                temp.append(i)
            picked = random.choice(temp)
            puzzle[pos[0]][pos[1]] = picked
            block.append(picked)
        pick_options.append(temp_options)
    return puzzle, pick_options

  def get_energy(self, puzz):
    energy = 0
    for x in range(self.size):
      row_vals = np.zeros(self.size)
      column_vals = np.zeros(self.size)
      for y in range(self.size):
        row_vals[puzz[x][y] -1] += 1
        column_vals[puzz[y][x] - 1] += 1
      energy += sum(row_vals != 1) + sum(column_vals != 1)
    
    thermometers = [[[1,1],[0,1],[0,0],[1,0],[2,0]],
                    [[3,0],[3,1],[3,2]],
                    [[2,3],[3,3]],
                    [[0,2],[1,2],[2,1]],
                    [[1,2],[1,3],[2,2]],
                    [[1,5],[1,4],[2,5],[3,4],[2,4]],
                    [[0,6],[0,5]],
                    [[0,6],[0,7]],
                    [[0,6],[1,6],[2,6],[3,5]],
                    [[2,7],[3,7],[3,8],[2,8],[1,8],[1,7]],
                    [[5,2],[5,3],[4,2],[5,1],[6,2]],
                    [[7,0],[6,0],[7,1],[6,1],[7,2]],
                    [[5,4],[5,5],[5,6]],
                    [[5,4],[6,4],[7,4],[8,3]],
                    [[6,4],[6,5]],
                    [[7,6],[7,7],[6,6],[7,5],[8,6]],
                    [[8,8],[8,7],[7,8],[6,8],[5,8]]]
    
    for thermometer in thermometers:
      for x in range(len(thermometer) - 1):
        if puzz[thermometer[x][0]][thermometer[x][1]] > puzz[thermometer[x+1][0]][thermometer[x+1][1]]:
          energy += 1

    return energy
    
  def swap_and_check(self, a, b):
    temp_puzzle = np.copy(self.puzzle)
    temp_puzzle[a[0]][a[1]] = self.puzzle[b[0]][b[1]]
    temp_puzzle[b[0]][b[1]] = self.puzzle[a[0]][a[1]]

    delta = self.get_energy(temp_puzzle) - self.energy
    temp = math.exp(-delta/self.temperature)
    if(np.random.uniform(1,0,1) < temp):
      self.energy = self.get_energy(temp_puzzle)
      self.err = 0
      return temp_puzzle
    else:
      self.err += 1
      return self.puzzle
  
  def step(self):
    for x in range(self.itterations):
      box_no = random.randint(0,self.size - 1)
      choices = self.pick_options[box_no]
      if len(choices) != 0:
        vals = random.sample(choices, 2)
        self.puzzle = self.swap_and_check(vals[0], vals[1])
    self.temperature *= self.cooling_rate
    if self.err > 180:
      self.temperature += 1.2
      self.err = 0

In [ ]:
e = [[0, 0, 1, 0, 9, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 9, 0],
 [0, 0, 0, 2, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 9],
 [0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 9, 0, 0]]

solver = simulatedAnnealing(e, 9, 0.99)
while solver.energy != 0:
  solver.step()
  print(solver.energy)

Streaming output truncated to the last 5000 lines.
23
23
23
23
20
20
18
18
18
18
15
15
15
15
15
15
14
14
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
12
12
12
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
17
17
15
15
15
17
17
20
21
21
25
25
25
25
18
18
18
18
18
18
18
18
19
19
19
19
18
19
19
19
19
18
18
22
17
17
17
17
17
18
17
17
17
17
17
17
17
17
17
16
16
16
19
15
15
16
21
21
21
21
21
21
25
25
25
25
25
25
22
22
22
22
22
22
22
22
22
22
22
22
22
22
20
20
20
20
20
20
20
20
20
16
16
16
16
16
16
16
16
15
15
15
10
10
10
10
10
10
10
10
10
10
10
10
10
10
15
15
11
11
11
11
11
15
18
27
27
33
33
28
26
28
30
19
18
18
19
20
22
19
19
17
17
18
18
22
22
21
21
21
21
25
25
25
24
25
25
25
25
25
28
29
26
26
24
20
21
25
28
27
27
22
21
21
21
22
21
21
21
21
21
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
23
23
23
23
23
23
23
23
23
23
23
23
23
2

In [4]:
[[0, 0, 1, 0, 9, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 9, 0],
 [0, 0, 0, 2, 0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 9],
 [0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 9, 0, 0]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(solver.puzzle)

[[2 4 3 9 1 5 8 6 7]
 [8 6 5 4 2 7 1 9 3]
 [7 9 1 6 8 3 5 2 4]
 [5 8 6 1 3 2 7 4 9]
 [4 3 7 5 9 8 6 1 2]
 [9 1 2 7 6 4 3 5 8]
 [3 7 4 2 5 6 9 8 1]
 [1 5 8 3 4 9 2 7 6]
 [6 2 9 8 7 1 4 3 5]]
