<a href="https://colab.research.google.com/github/JamieBali/sudoku/blob/main/WFC_Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [ ]:
import numpy as np
import random
import math
import tensorflow as tf

# Data

In [ ]:
trivial = [[8,9,1,2,7,0,5,6,3],[6,0,3,1,8,5,9,0,0],[4,5,7,6,3,9,0,0,2],[5,0,6,4,1,7,2,3,0],[7,0,2,9,0,3,8,1,6],[3,1,0,0,2,6,0,5,4],[9,3,8,5,4,0,6,7,0],[1,6,4,0,9,0,3,2,5],[0,7,5,3,6,1,4,9,8]]

# this is a very simple 4x4 sudoku from sudoku.com
four = [[0,3,4,0],[4,0,0,2],[1,0,0,3],[0,2,1,0]]

# these three were taken randomly from sudoku.com
easy = [[0,0,0,0,7,9,0,3,0],[5,0,2,0,6,1,4,7,8],[3,7,6,0,8,5,9,0,2],[0,1,7,5,0,0,8,0,0],[2,0,9,8,3,0,0,0,0],[0,0,0,0,2,0,0,4,0],[0,0,0,0,5,0,2,0,1],[0,2,3,0,0,0,0,5,4],[1,0,0,7,0,0,0,0,0]]
medium = [[0,3,1,0,5,0,0,2,0],[0,0,0,0,0,2,9,0,5],[2,0,0,0,1,0,0,0,0],[3,5,0,0,9,0,0,7,0],[7,0,0,5,0,0,0,4,0],[0,1,0,7,0,3,2,0,0],[1,2,6,3,0,0,0,0,0],[0,9,0,8,0,5,0,0,0],[5,0,0,0,2,0,7,0,0]]
hard = [[0,4,0,0,0,5,0,6,0],[0,0,5,4,2,0,0,0,0],[0,0,1,6,0,3,5,0,4],[0,0,0,0,0,0,7,0,0],[0,3,7,0,0,0,0,1,0],[9,0,0,0,0,4,3,5,0],[0,0,4,2,5,0,0,0,0],[0,0,0,0,0,0,0,7,6],[6,0,9,0,7,0,0,0,5]]

# this is a 25x25 sudoku taken from an old c programming forum in from 2006 https://cboard.cprogramming.com/cplusplus-programming/117005-25x25-sudoku.html
twentyfive = [[0,0,12,6,0,0,7,0,18,0,5,24,0,10,1,0,0,4,0,0,0,0,0,0,0], [2,0,19,0,13,0,0,0,10,0,0,0,0,0,0,0,0,18,5,0,0,0,0,0,1], [0,0,0,0,0,0,0,22,0,0,0,0,3,0,2,0,0,14,12,0,16,8,25,0,0],[0,16,0,0,0,2,23,0,0,13,12,22,0,0,0,21,15,19,3,0,0,0,0,14,0],[23,0,24,0,0,0,0,0,25,8,4,0,16,19,21,0,0,7,0,0,0,3,12,0,9],[0,4,0,2,0,0,0,0,0,0,0,10,0,24,12,17,16,0,0,0,5,0,0,0,0],[0,0,9,0,0,6,25,0,0,0,8,0,5,3,0,0,0,0,0,0,20,0,0,18,19],[15,0,10,11,0,0,0,18,12,19,0,0,0,0,0,0,0,23,0,0,7,0,0,4,0], [0,0,0,0,0,0,0,14,0,22,0,0,18,16,20,0,6,11,13,0,0,0,0,0,0], [0,22,0,25,0,0,1,17,5,4,7,0,0,14,0,8,3,21,0,0,11,0,0,0,6], [0,20,13,15,0,0,0,0,0,0,9,0,0,2,0,25,0,1,8,0,0,5,0,21,0], [0,1,0,0,0,0,16,10,0,7,0,0,4,20,0,0,9,0,0,14,0,24,0,17,0], [25,2,5,0,0,0,0,0,13,0,0,0,0,0,22,0,0,0,0,0,19,1,8,0,0], [0,0,7,21,0,0,12,0,2,17,0,0,0,18,6,16,0,0,15,0,0,13,0,10,0], [8,10,18,12,16,9,0,0,0,5,0,0,0,0,19,0,0,17,0,21,0,15,0,0,22], [0,8,0,0,15,0,3,0,6,0,21,0,0,7,0,18,14,5,0,1,0,0,0,0,0], [0,0,0,19,0,1,0,16,11,0,0,0,10,22,25,15,0,0,0,0,0,0,21,0,0], [0,3,1,0,21,0,0,4,0,0,0,0,2,0,13,0,24,25,0,0,14,0,0,6,0], [0,0,0,0,0,0,0,15,0,12,14,0,6,17,24,0,0,0,0,0,0,0,13,0,0], [0,5,23,16,4,0,13,24,7,2,0,9,0,0,15,3,0,22,0,0,0,0,0,0,8], [0,0,25,20,2,0,19,0,0,0,0,1,0,0,0,0,21,3,0,0,12,0,0,0,0], [16,12,0,5,0,11,21,0,23,0,0,15,0,0,0,0,19,9,0,0,0,0,0,25,10], [0,0,0,0,9,20,22,7,4,0,3,0,14,25,18,0,11,0,0,0,0,0,1,0,15], [24,0,6,0,22,8,0,25,14,0,10,11,0,9,0,20,1,16,0,7,0,23,0,0,13], [14,13,21,1,0,0,5,0,0,0,6,0,22,0,23,10,0,0,0,2,0,0,18,7,11]]

# this is the solved version of the "easy" sudoku above.
solved = [[8,4,1,2,7,9,6,3,5],[5,9,2,3,6,1,4,7,8],[3,7,6,4,8,5,9,1,2],[4,1,7,5,9,6,8,2,3],[2,5,9,8,3,4,1,6,7],[6,3,8,1,2,7,5,4,9],[7,6,4,9,5,3,2,8,1],[9,2,3,6,1,8,7,5,4],[1,8,5,7,4,2,3,9,6]]

# Wave Function Collapse

In [ ]:
class waveFunction():
  def __init__(self, size = 9):
    self.size = size
    self.wave = self.construct_superpositions()
  
  ###
  # Generates a stepwise numpy array - for dynamic functionality
  ###
  def stepwise_array(self):
    arr = []
    for x in range(self.size):
      arr.append(x+1)
    return np.array(arr)

  ###
  # Creates the initial 9x9 grid in a superposition of 9 eigenstates
  ###
  def construct_superpositions(self):
    return np.array([[self.stepwise_array() for x in range(self.size)] for y in range(self.size)])

  ###
  # Clears the eigenstates of positions that were given at the start, 
  # then propogates the waves outwards from them.
  ###
  def initialise_eigenstates(self, wave, board):
    for x in range(self.size):
      for y in range(self.size):
        val = board[x][y]
        if val != 0:
          wave[x][y] = np.zeros(self.size)
          wave = self.propogate_wave(wave, x, y, val)
    return wave

  ###
  # Propogates wave outwards, clearing any clashing eigenstates.
  # (i.e. removes states from positions which would violate the rules of Sudoku)
  ###
  def propogate_wave(self, wave, start_x, start_y, start_z):
    for x in range(self.size):      
        wave[x][start_y][start_z-1] = 0   # since z refers to the numerical value, we need z-1 for the list location
        wave[start_x][x][start_z-1] = 0   
    rt = int(math.sqrt(self.size))
    box_x = (start_x // rt) * rt      # find co-ordinates of lowest corner in the sub-grid
    box_y = (start_y // rt) * rt  
    for x_itt in range(rt):          # itterators for sub-grids
      for y_itt in range(rt):
        wave[box_x + x_itt][box_y+y_itt][start_z-1] = 0

    ### Further propogation - check for exclusivity in rows, columns, and boxes.
      # If we say that the initial propogation is 1st-degree propogation,
      # this is 2nd-degree.
      # This will slow down our system, but may allow it to solve harder problems
      # with a higher degree of accuracy.
      # We can, of course, go further than this, checking for naked pairs,
    ### hidden sets, and X-wings, but we won't here.

    for x in range(self.size):
      indexes = np.zeros(self.size + 1)
      vals = np.zeros(self.size + 1)      # this is 10 long instead of 9, so we don't have 
      for y in range(self.size):                # to have an extra if statement checking for 0s
        for z in range(self.size):
          vals[wave[x][y][z]] += 1
          indexes[wave[x][y][z]] = y

      for v in range(self.size):                # check through the vals
        if vals[v+1] == 1:              # if it's 1, then we can make that 1 a given
          wave[x][int(indexes[v+1])] = np.zeros(self.size)   # since we kept an index list, this becomes easier
          wave[x][int(indexes[v+1])][v] = v+1                         
                                                # we then repeat for the other caridnal
    for y in range(self.size):                          # x and y itterations swapped
      indexes = np.zeros(self.size + 1) 
      vals = np.zeros(self.size + 1)        
      for x in range(self.size):                
        for z in range(self.size):
          vals[wave[x][y][z]] += 1
          indexes[wave[x][y][z]] = x            # alter x insteaf of y
      for v in range(self.size):                
        if vals[v+1] == 1:              
          wave[int(indexes[v+1])][y] = np.zeros(self.size)      # and switch co-ordinates
          wave[int(indexes[v+1])][y][v] = v+1

    for box_x in range(rt):    # for each sib-grid seperately
      for box_y in range(rt):
        x_indexes = np.zeros(self.size + 1)
        y_indexes = np.zeros(self.size + 1)  
        vals = np.zeros(self.size + 1) 
        for x in range(rt):
          for y in range(rt):
            for z in range(self.size):
              vals[wave[(rt * box_x) + x][(rt * box_y) + y][z]] += 1
              x_indexes[wave[(rt * box_x) + x][(rt * box_y) + y][z]] = (rt * box_x) + x  
              y_indexes[wave[(rt * box_x) + x][(rt * box_y) + y][z]] = (rt * box_y) + y
        for v in range(self.size):
          if vals[v+1] == 1:
            wave[int(x_indexes[v+1])][int(y_indexes[v+1])] = np.zeros(self.size) 
            wave[int(x_indexes[v+1])][int(y_indexes[v+1])][v] = v+1

    return wave
  
  ###
  # If there is a tile in the board that is unfilled, but has no eigenstates, the board is invalid.
  # We can use this invalidity to check for vioaltions, disallowing invalid moves. 
  # (i.e. a number may be valid in a tile, but it would invalidate another. Ipso factor, invalid placement)
  ###
  def is_valid(self, wave, board):
    for x in range(self.size):
      for y in range(self.size):
        if board[x][y] == 0 and wave[x][y].sum() == 0:
          return False
    return True

  ###
  # Gets the number of eigenstates in a given position.
  # This acts as an inverse probability of a eigenstate belonging in a certain position.
  # If a value of size + 1 is returned, then the position is empty.
  # A position becomes empty when an eigenstate gets chosen, or through erroneous placement.
  # We do this instead of returning 0 for an empty position, as we need to use a min() function later.
  # If min of all tiles is size + 1, then all positions are empty. Ipso facto, sudoku complete.
  ###
  def num_eigenstates(self, eigenstates):
    num = np.array(eigenstates != 0).sum()
    if num == 0:
      return self.size + 1
    else:
      return num

  ###
  # Here we observe the wave, doing the majority of our processing.
  # We need to check for which wave has the least superpositions.
  # If the given superposition has only one eigenstate, then we return it,
  # along with a tag that says it is a given value, else we return one of the
  # eigenstates at random, with a tag that says it was randomly picked.
  ###
  def observe(self, wave):                                      
    mask = []             # the mask lists how many eigenstates each position contains
    for x in range(self.size):
      temp = []
      for y in range(self.size):
        temp.append(self.num_eigenstates(wave[x][y]))
      mask.append(temp)

    if np.array(mask).min() == self.size + 1:   # if the lowest number of eigenstates across the whole mask is size + 1,
                                                # then we know there are no valid moves available (since size + 1 means
                                                # the position is empty)
      return -1, -1, -1, False                  # we return -1 as an erroneous marker to be identified, and an 
                                                # arbitrary tag since it won't be checked.

    ind = np.array(mask).argmin()                   # find the index of the position with the least eigenstates
    x, y = (ind // self.size), (ind % self.size)    # unflatten
    temp = wave[x][y]                               # get the list of eigenstates for that position
    temp2 = []      
    for v in temp:                  # create a list of non-0 states
      if v != 0:
        temp2.append(v)
    if len(temp2) == 1:             # if the list has a length of 1, it's a given value
      return x, y, temp2[0], True
    return x, y, random.choice(temp2), False    # else randomly pick.

  ###
  # Here we take a single step, finding an optimal move, and then checking it is 
  # valid after propogation to decide whether or not it is valid.
  ###
  def step(self, wave, board, verbose):
    if verbose:
      print("making observation")
    x, y, val, given = self.observe(wave) # make an observation of the system
                                          # the observation returns co-ordinates of
                                          # an optimal move, the value it should be, 
                                          # and whether or not it was a given.

    if x == -1:                           # -1 is an erroneous marker to flag that                                    
      return wave, board, True            # all positions in the wave are empty, so
                                          # we can end processing
    if verbose:
      print("propogating wave")
    board[x][y] = val                                       # fill in the value
    wave[x][y] = np.zeros(self.size)                        # empty the respective position in the wave
    propogated_wave = self.propogate_wave(wave, x, y, val)  # create a seperate variable for the propogated
                                                            # wave, lest it need to be reverted.
    if self.is_valid(wave, board):
      if verbose:
        print("eigenstate accepted")  
      return propogated_wave, board, False    # if the move is valid, return the propogated wave
                                              # and the new board state, as well as a flag to continue
    else:
      if given:                         # if the move is invalid, and a given, there was an error.
        if verbose:                     # halt processing.
          print("board state error")        
        return wave, board, True 
      if verbose:
        print("invalid eigenstate being removed")
      wave[x][y][val-1] = 0             # if the move is invalid and not given, remove that eigenstate from the un-propogated wave
      return wave, board, False         # then try again.

  ###
  # This function brings the system together to function full from one command.
  # We take puzzle as an input, and return the final board state, as well as a
  # boolean saying whetheter or not the puzzle is actually complete.
  ###
  def solve(self, puzzle, verbose = False):
    if verbose:
      print("constructing board")
    self.board = np.array(puzzle).reshape((self.size, self.size))   # fill the board
    if verbose:
      print("constructing wave function")
    self.wave = self.initialise_eigenstates(self.wave, self.board)  # initialise the wave function
    solved = False
    steps = 1
    while not solved:
      if verbose:
        print("step no: " + str(steps))
      self.wave, self.board, solved = self.step(self.wave, self.board, verbose)
      steps += 1
    if verbose:
      print("wave collapsed")
    if np.array(self.board == 0).sum() == 0:
      return self.board, True
    else:
      return self.board, False

In [ ]:
size = 9
wf = waveFunction(size)
solution, solved = wf.solve(hard, False)
print(solution)

[[2 4 3 9 1 5 8 6 7]
 [8 6 5 4 2 7 1 9 3]
 [7 9 1 6 8 3 5 2 4]
 [5 8 6 1 3 2 7 4 9]
 [4 3 7 5 9 8 6 1 2]
 [9 1 2 7 6 4 3 5 8]
 [3 7 4 2 5 6 9 8 1]
 [1 5 8 3 4 9 2 7 6]
 [6 2 9 8 7 1 4 3 5]]


# Accuracy Test

This is the same accuracy test we are using on all the solvers we are making.

In [ ]:
import os
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd

filepath = "/content/gdrive/My Drive/ColabNotebooks/IP/sudoku.csv"
inp = pd.read_csv(filepath)
test_puzzles = inp["quizzes"]
test_solutions = inp["solutions"]

Mounted at /content/gdrive


In [ ]:
tests = []
solutions = []
for x in range(990000, 999999):
  tests.append(np.array([int(t) for t in test_puzzles[x]]).reshape((9,9)))
  solutions.append(np.array([int(t) for t in test_solutions[x]]).reshape((9,9)))

In [ ]:
with tf.device('/device:GPU:0'):
  corr = 0

  for x in range(len(tests)):
    print(str(x) + " / " + str(len(tests)))
    wf = waveFunction(9)
    solution, solved = wf.solve(tests[x], False)
    if solved:
      corr += 1
  print("Accuracy : " + str(np.around((corr/len(tests) * 100),2)) + "%")

# Accuracy : 99.86, meaning it got 14 of them wrong.

Accuracy : 99.86%
